USER_EXPIRE_SECONDS = 30
BOT_ARENA_HISTORY_KEY = "bot_arena_history"
BOT_ARENA_MAX_MSGS = 30
MULTIBOT_HISTORY_KEY = "multibot_history:all"
MULTIBOT_MAX_TURNS = 20
MULTIBOT_HISTORY_COUNT = 40
MULTIBOT_ANSWER_TEMPERATURE = 0.6
